tap "aws/tap"
tap "bufbuild/buf"
tap "buo/cask-upgrade"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Official Amazon AWS command-line interface
brew "awscli"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Docker Credential Helper for Amazon ECR
brew "docker-credential-helper-ecr", link: false
# Tool for managing dock items
brew "dockutil"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# Small git utilities
brew "git-extras"
# Git extension for versioning large files
brew "git-lfs"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Image manipulation
brew "netpbm"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Kubernetes package manager
brew "helm"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Kubernetes command-line interface
brew "kubernetes-cli", link: false
# Template-free customization of Kubernetes YAML manifests
brew "kustomize"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# Node version management
brew "n"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# UNIX shell (command interpreter)
brew "zsh"
# A new way of working with Protocol Buffers.
brew "bufbuild/buf/buf"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# API documentation browser and code snippet manager
cask "dash"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "google-chrome"
# Desktop automation application
cask "hammerspoon"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# Collaboration platform for API development
cask "postman"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
mas "Magnet", id: 441258766
mas "Xcode", id: 497799835
vscode "aaron-bond.better-comments"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "bufbuild.vscode-buf"
vscode "castwide.solargraph"
vscode "dbaeumer.vscode-eslint"
vscode "deerawan.vscode-dash"
vscode "dnicolson.binary-plist"
vscode "eamodio.gitlens"
vscode "eg2.vscode-npm-script"
vscode "firsttris.vscode-jest-runner"
vscode "folke.vscode-monorepo-workspace"
vscode "GitHub.vscode-pull-request-github"
vscode "golang.go"
vscode "hbenl.vscode-mocha-test-adapter"
vscode "hbenl.vscode-test-explorer"
vscode "jebbs.plantuml"
vscode "jingkaizhao.vscode-redux-devtools"
vscode "kddejong.vscode-cfn-lint"
vscode "mark-tucker.aws-cli-configure"
vscode "mgmcdermott.vscode-language-babel"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.test-adapter-converter"
vscode "msjsdiag.vscode-react-native"
vscode "ninoseki.vscode-gem-lens"
vscode "njpwerner.autodocstring"
vscode "numso.prettier-standard-vscode"
vscode "Orta.vscode-jest"
vscode "plex.vscode-protolint"
vscode "rebornix.ruby"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "samuelcolvin.jinjahtml"
vscode "standard.vscode-standard"
vscode "Tim-Koehler.helm-intellisense"
vscode "twxs.cmake"
vscode "wingrunr21.vscode-ruby"
vscode "zxh404.vscode-proto3"
